### PR TITLE
Create APIStuff.hx so that no one else has to lol

### PR DESCRIPTION
**Pull request by AmberHaxe**
Create APIStuff.hx so that no one else has to lol

### CODE REVIEW

**Comment by DotWith** [comment]
Maybe but you should find how to secure the API and EncKey. Encrypt it?

**Comment by prokube** [comment]
> Maybe but you should find how to secure the API and EncKey. Encrypt it?

you literally don't need the api and enckey. just leave it alone

**Comment by DotWith** [comment]
> > Maybe but you should find how to secure the API and EncKey. Encrypt it?
> 
> you literally don't need the api and enckey. just leave it alone unless you're doing stuff with servers
> 
> edit: im stupid you guys have an online server okay carry on

I use the real fnf api and enc key... I wonder on leaderboard if it says I played expurgation.

**Comment by DotWith** [comment]
So is the gitignore fine with this?

**Comment by prokube** [comment]
> I use the real fnf api and enc key... I wonder on leaderboard if it says I played expurgation.

expurgation canon in fnf according to leaderboards?????? :a:

**Pull request merged**
