### PR TITLE
update project xml

### PR DESCRIPTION
**Pull request by MrClogsworthYT**
makes a new folder on app data instead of using that boring ninjamuffin folder

### CODE REVIEW

**Review by ACrazyTown — CHANGES_REQUESTED** [review]
you should probably change it a bit, maybe something like
`<app title="Friday Night Funkin': Dot Engine" file="DotEngine" packageName="com.dotwith.dotengine" package="com.dotwith.dotengine" main="Main" version="0.2.7.1" company="DotWith" />`

**Comment by MrClogsworthYT** [comment]
> <app title="Friday Night Funkin': Dot Engine" file="DotEngine" packageName="com.dotwith.dotengine" package="com.dotwith.dotengine" main="Main" version="0.2.7.1" company="DotWith" />

copypasted

**Comment by DotWith** [comment]
It's supposed to get your saves from normal fnf.

**Comment by MrClogsworthYT** [comment]
> It's supposed to get your saves from normal fnf.

lets be honest 
who tf would download the normal game on these days
besides they can just drag and drop the funkin data file

**Comment by DotWith** [comment]
I don't like the idea

**Comment by MrClogsworthYT** [comment]
> 

k

**Comment by AbnormalPoof** [comment]
> who tf would download the normal game on these days
amogus

**Pull request closed without merging**
